#!/bin/bash

# 检测脚本文件是否存在，存在则执行
if [ -f "${SCNET_USER_HOME}/scripts/link_models.sh" ]; then
    bash "${SCNET_USER_HOME}/scripts/link_models.sh" && echo "模型文件连接完成！"
else
    echo "提示: link_models.sh 文件不存在，跳过执行。请手动处理模型文件后刷新ComfyUI浏览器界面。"
fi

pip install "numpy<2" --force-reinstall --no-cache-dir -i https://mirrors.cloud.tencent.com/pypi/simple/

cd /app/ComfyUI
python main.py --listen --port 3000 --enable-cors-header
